USE LLIBRERIA;
DELIMITER //
DROP PROCEDURE IF EXISTS sp01_Llibre_Aprop_Estoc//
CREATE PROCEDURE sp01_Llibre_Aprop_Estoc()
SELECT TITOL, EDITORIAL, ESTOC
    FROM LLIBRES WHERE ESTOC <= 5;
END //
DELIMITER ;