USE LLIBRERIA;
DELIMITER //
DROP PROCEDURE IF EXISTS sp03_Llibres_Autor//
CREATE PROCEDURE sp03_Llibres_Autor(
IN p_autor varchar(30))
BEGIN 
    SELECT TITOL, EDITORIAL, PREU
    FROM LLIBRES WHERE AUTOR = p_autor;
END //
DELIMITER ;